// starting point generated by claude sonnet 4.5 and edited manually
package com.example.composetutorial.utils

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import androidx.core.app.NotificationCompat
import com.example.composetutorial.R

const val CHANNEL_ID = "default_channel"

fun createNotificationChannel(context: Context) {
    val importance = NotificationManager.IMPORTANCE_DEFAULT
    val channel = NotificationChannel(CHANNEL_ID, "Notifications", importance).apply {
        description = "Default notification channel for the app"
    }

    val notificationManager: NotificationManager =
        context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    notificationManager.createNotificationChannel(channel)
}

fun showNotification(
    context: Context,
    title: String = "Hello!",
    message: String = "This is a test notification",
    pendingIntent: PendingIntent? = null
) {
    val notificationManager =
        context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

    val builder = NotificationCompat.Builder(context, CHANNEL_ID)
        .setSmallIcon(R.drawable.ic_launcher_foreground)
        .setContentTitle(title)
        .setContentText(message)
        .setPriority(NotificationCompat.PRIORITY_DEFAULT)
        .setAutoCancel(true)

    if (pendingIntent != null) builder.setContentIntent(pendingIntent)

    notificationManager.notify(System.currentTimeMillis().toInt(), builder.build())
}

